#!/usr/bin/env python3
# Copyright (c) 2024-2026 ScreenerBot (screenerbot.io)
# SPDX-License-Identifier: BUSL-1.1

"""Per-script dashboard fonts: download, subset, rename and describe.

Input is `tools/fonts/fonts.json` (hand-maintained). Outputs:

- `src/webserver/assets/fonts/<file>` and `<license_file>` for every face;
- `tools/fonts/coverage.json`: hash, size, weight, locales, unicode-range, metric overrides and the
  effective codepoint coverage of every bundled font (read by tools/tests/script_fonts.test.mjs);
- `src/webserver/templates/styles/base/script_fonts.css`: one @font-face per face.

Sources are single files pinned by tag or commit and by sha256. `--pin` fills sha256 values that
are still empty (first run only); afterwards a mismatch is fatal. `--check` rebuilds into a
temporary directory and compares every output with the committed file. The tool runs by hand in a
throwaway virtualenv; nothing here runs during `cargo build` or at runtime.

    python3 -m venv /tmp/sbfonts
    /tmp/sbfonts/bin/pip install -r tools/fonts/requirements.txt
    /tmp/sbfonts/bin/python tools/fonts/build_fonts.py [--pin | --check]

Subset faces are processed in this order: load (lazy=False), subset, instance the variable axes,
rename, save as WOFF2. Instancing before subsetting fails on the Noto sources (gvar KeyError).
A subset is a Modified Version under the OFL, so a subset face must not carry a Reserved Font Name
from its license; such faces are renamed to `css_family` in the name table.
"""

from __future__ import annotations

import argparse
import hashlib
import io
import json
import re
import sys
import tempfile
import tomllib
import urllib.parse
import urllib.request
from pathlib import Path

import fontTools
from fontTools import subset
from fontTools.pens.boundsPen import BoundsPen
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

TOOL_DIR = Path(__file__).resolve().parent
REPO_ROOT = TOOL_DIR.parent.parent
MANIFEST = TOOL_DIR / "fonts.json"
COVERAGE = TOOL_DIR / "coverage.json"
FONTS_DIR = REPO_ROOT / "src/webserver/assets/fonts"
STYLES_DIR = REPO_ROOT / "src/webserver/templates/styles"
SCRIPT_FONTS_CSS = STYLES_DIR / "base/script_fonts.css"
FOUNDATION_CSS = STYLES_DIR / "foundation.css"
LOCALES_DIR = REPO_ROOT / "locales"
CACHE_DIR = Path.home() / ".cache/screenerbot-fonts"

# Name records kept verbatim when a face is renamed: copyright, trademark, manufacturer,
# designer, description, vendor/designer URLs, license and license URL.
PRESERVED_NAME_IDS = {0, 7, 8, 9, 10, 11, 12, 13, 14}
# Inter's metrics are the reference line box for faces with `metrics: "inter"`.
INTER_FILE = "Inter-Variable.woff2"
PRINT_WIDTH = 100  # .prettierrc.json printWidth; the JSON emitter wraps like prettier.
CSS_HEADER = "/* Generated by tools/fonts/build_fonts.py from tools/fonts/fonts.json; do not edit. */"


class BuildError(Exception):
    """A pin, count, coverage or licensing invariant does not hold."""


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


# ---------------------------------------------------------------------------------------------
# Sources
# ---------------------------------------------------------------------------------------------


def fetch(url: str) -> bytes:
    """Bytes of `url`, served from the download cache when present."""
    name = urllib.parse.unquote(url.rsplit("/", 1)[-1])
    cached = CACHE_DIR / f"{hashlib.sha256(url.encode()).hexdigest()[:16]}-{name}"
    if cached.exists():
        return cached.read_bytes()
    print(f"  download {url}")
    request = urllib.request.Request(url, headers={"User-Agent": "screenerbot-build-fonts"})
    with urllib.request.urlopen(request, timeout=120) as response:
        data = response.read()
    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    cached.write_bytes(data)
    return data


def pinned(face: dict, key: str, data: bytes, pin: bool, pins: dict) -> None:
    """Verify `data` against `face[key]`, or record the hash when pinning an empty value."""
    actual = sha256(data)
    expected = face.get(key, "")
    if expected:
        if expected != actual:
            raise BuildError(f"{face['file']}: {key} is {actual}, fonts.json pins {expected}")
    elif pin:
        pins[(face["file"], key)] = actual
        face[key] = actual
    else:
        raise BuildError(f"{face['file']}: {key} is empty; run once with --pin")


def write_pins(pins: dict) -> None:
    """Fill empty sha256 values in fonts.json in place, keeping its hand formatting."""
    text = MANIFEST.read_text(encoding="utf-8")
    for (file, key), value in pins.items():
        start = text.index(f'"file": "{file}"')
        end = text.find('"file": "', start + 1)
        end = len(text) if end < 0 else end
        field = f'"{key}": ""'
        at = text.index(field, start, end)
        text = text[:at] + f'"{key}": "{value}"' + text[at + len(field) :]
    MANIFEST.write_text(text, encoding="utf-8")


def reserved_names(license_text: str) -> list[str]:
    """Reserved Font Names declared in the copyright preamble of an OFL license text."""
    preamble = license_text.split("This Font Software is licensed", 1)[0]
    names = []
    for match in re.finditer(r"Reserved Font Names?\s+(.+?)(?:\.\s|\.?$)", preamble, re.M):
        declared = match.group(1)
        quoted = re.findall(r"[\"'“‘]([^\"'”’]+)[\"'”’]", declared)
        names.extend(quoted or [part.strip() for part in re.split(r",| and ", declared)])
    return [name for name in names if name]


# ---------------------------------------------------------------------------------------------
# Character sets
# ---------------------------------------------------------------------------------------------


def parse_ranges(ranges: list[str]) -> list[tuple[int, int]]:
    """`["3000-303F", "25CC"]` as inclusive integer pairs."""
    pairs = []
    for item in ranges:
        low, _, high = item.partition("-")
        pairs.append((int(low, 16), int(high or low, 16)))
    return pairs


def in_ranges(codepoint: int, pairs: list[tuple[int, int]]) -> bool:
    return any(low <= codepoint <= high for low, high in pairs)


def codec_rows(codec: str, rows: list[int]) -> set[int]:
    """Characters of EUC rows `rows[0]..rows[1]`: lead byte 0xA0+row, trail bytes 0xA1..0xFE."""
    chars = set()
    for row in range(rows[0], rows[1] + 1):
        for trail in range(0xA1, 0xFF):
            try:
                text = bytes([0xA0 + row, trail]).decode(codec)
            except UnicodeDecodeError:
                continue
            if len(text) == 1:
                chars.add(ord(text))
    return chars


def registry_names() -> dict[str, str]:
    with (LOCALES_DIR / "registry.toml").open("rb") as handle:
        return {entry["code"]: entry["name"] for entry in tomllib.load(handle)["locale"]}


def catalog_codepoints(code: str) -> set[int]:
    """Every codepoint >= U+0080 in `locales/<code>/*.ftl` plus the locale's native name."""
    text = registry_names()[code]
    for path in sorted((LOCALES_DIR / code).glob("*.ftl")):
        text += path.read_text(encoding="utf-8")
    return {ord(char) for char in text if ord(char) >= 0x80}


def charset(face: dict, source_cmap: dict, report: dict) -> set[int]:
    """The codepoints a face must carry. Catalog characters inside its unicode-range must exist in
    the source; codec rows must decode to exactly the expected number of characters."""
    unicode_range = parse_ranges(face["unicode_range"])
    wanted = set()
    for entry in face["charset"]:
        if "codec" in entry:
            chars = codec_rows(entry["codec"], entry["rows"])
            if len(chars) != entry["expect"]:
                raise BuildError(
                    f"{face['file']}: {entry['codec']} rows {entry['rows']} decode to {len(chars)} "
                    f"characters, fonts.json expects {entry['expect']}"
                )
            report[f"{entry['codec']} rows {entry['rows'][0]}-{entry['rows'][1]}"] = len(chars)
            wanted |= chars
        elif "ranges" in entry:
            for low, high in parse_ranges(entry["ranges"]):
                wanted |= set(range(low, high + 1))
        elif "catalog" in entry:
            chars = {cp for cp in catalog_codepoints(entry["catalog"]) if in_ranges(cp, unicode_range)}
            missing = sorted(cp for cp in chars if cp not in source_cmap)
            if missing:
                listed = ", ".join(f"U+{cp:04X}" for cp in missing)
                raise BuildError(f"{face['file']}: catalog {entry['catalog']} needs {listed}; absent from the source font")
            report[f"catalog {entry['catalog']}"] = len(chars)
            wanted |= chars
        else:
            raise BuildError(f"{face['file']}: unknown charset entry {entry}")
    return wanted


# ---------------------------------------------------------------------------------------------
# Font processing
# ---------------------------------------------------------------------------------------------


def load(data: bytes) -> TTFont:
    return TTFont(io.BytesIO(data), lazy=False, recalcTimestamp=False)


def family_name(font: TTFont) -> str:
    name = font["name"]
    return name.getDebugName(16) or name.getDebugName(1)


def rename(font: TTFont, family: str) -> None:
    """Replace the source family and PostScript family in every non-preserved name record."""
    name = font["name"]
    old_family = family_name(font)
    old_ps = name.getDebugName(25) or name.getDebugName(6).split("-", 1)[0]
    new_ps = family.replace(" ", "")
    for record in name.names:
        if record.nameID in PRESERVED_NAME_IDS:
            continue
        text = record.toUnicode()
        updated = text.replace(old_family, family).replace(old_ps, new_ps)
        if updated != text:
            record.string = updated


def check_reserved(face: dict, font: TTFont, reserved: list[str]) -> None:
    """A modified face must not use a Reserved Font Name in CSS or in its naming records."""
    for reserved_name in reserved:
        needle = reserved_name.casefold()
        if needle in face["css_family"].casefold():
            raise BuildError(f"{face['file']}: css_family contains Reserved Font Name {reserved_name!r}")
        for record in font["name"].names:
            if record.nameID not in PRESERVED_NAME_IDS and needle in record.toUnicode().casefold():
                raise BuildError(
                    f"{face['file']}: name ID {record.nameID} {record.toUnicode()!r} contains "
                    f"Reserved Font Name {reserved_name!r}"
                )


def build_subset(face: dict, source: bytes, reserved: list[str], report: dict) -> bytes:
    font = load(source)
    unicodes = charset(face, font.getBestCmap(), report)

    options = subset.Options()
    options.hinting = True
    options.notdef_outline = True
    options.name_IDs = ["*"]
    options.name_languages = ["*"]
    options.name_legacy = True
    if face["layout_features"] != "default":
        options.layout_features = face["layout_features"]
    subsetter = subset.Subsetter(options=options)
    subsetter.populate(unicodes=unicodes)
    subsetter.subset(font)

    limits = {axis: tuple(value) if isinstance(value, list) else value for axis, value in face["axes"].items()}
    instancer.instantiateVariableFont(font, limits, inplace=True)

    if family_name(font) != face["css_family"]:
        rename(font, face["css_family"])
    check_reserved(face, font, reserved)

    font.flavor = "woff2"
    output = io.BytesIO()
    font.save(output)
    return output.getvalue()


def glyph_height(font: TTFont, codepoint: int) -> float:
    """Outline bbox height of a character at the default instance, in em."""
    glyph_set = font.getGlyphSet()
    pen = BoundsPen(glyph_set)
    glyph_set[font.getBestCmap()[codepoint]].draw(pen)
    _, y_min, _, y_max = pen.bounds
    return (y_max - y_min) / font["head"].unitsPerEm


def default_weight(font: TTFont) -> float:
    return next(axis.defaultValue for axis in font["fvar"].axes if axis.axisTag == "wght")


def inter_metrics() -> dict:
    font = load((FONTS_DIR / INTER_FILE).read_bytes())
    os2, upm = font["OS/2"], font["head"].unitsPerEm
    return {
        "ascent": round(os2.sTypoAscender / upm, 6),
        "descent": round(-os2.sTypoDescender / upm, 6),
        "line_gap": round(os2.sTypoLineGap / upm, 6),
    }


def coverage_ranges(codepoints: set[int]) -> list[list[int]]:
    """Sorted codepoints as inclusive [low, high] runs."""
    runs: list[list[int]] = []
    for cp in sorted(codepoints):
        if runs and runs[-1][1] == cp - 1:
            runs[-1][1] = cp
        else:
            runs.append([cp, cp])
    return runs


def percent(value: float) -> str:
    return f"{value:.2f}".rstrip("0").rstrip(".") + "%"


# ---------------------------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------------------------


def committed_families() -> dict[str, str]:
    """File name -> font-family of the hand-written @font-face rules in foundation.css."""
    families = {}
    for block in re.findall(r"@font-face\s*\{([^}]*)\}", FOUNDATION_CSS.read_text(encoding="utf-8")):
        family = re.search(r"font-family:\s*\"?([^\";]+?)\"?\s*;", block).group(1)
        file = re.search(r"url\(\"?/assets/fonts/([^\")]+)\"?\)", block).group(1)
        families[file] = family
    return families


def to_json(value, indent: int = 0, prefix: int = 0) -> str:
    """JSON that `prettier` leaves unchanged: objects always expanded, arrays inline when the
    line (including `prefix` columns and a trailing comma) fits the print width."""
    pad = "  " * indent
    if isinstance(value, dict):
        if not value:
            return "{}"
        items = []
        for key, item in value.items():
            head = f"{pad}  {json.dumps(key, ensure_ascii=False)}: "
            items.append(head + to_json(item, indent + 1, len(head)))
        return "{\n" + ",\n".join(items) + f"\n{pad}}}"
    if isinstance(value, list):
        if not value:
            return "[]"
        if not any(isinstance(item, dict) for item in value):
            flat = "[" + ", ".join(to_json(item) for item in value) + "]"
            if prefix + len(flat) + 1 <= PRINT_WIDTH and "\n" not in flat:
                return flat
        items = [f"{pad}  " + to_json(item, indent + 1, len(pad) + 2) for item in value]
        return "[\n" + ",\n".join(items) + f"\n{pad}]"
    return json.dumps(value, ensure_ascii=False)


def font_face_css(face: dict, entry: dict) -> str:
    lines = [
        "@font-face {",
        f'  font-family: "{face["css_family"]}";',
        "  font-style: normal;",
        f"  font-weight: {face['weight'][0]} {face['weight'][1]};",
        "  font-display: swap;",
        f'  src: url("/assets/fonts/{face["file"]}") format("woff2");',
        f"  unicode-range: {entry['unicode_range']};",
    ]
    if entry["size_adjust"] != 100:
        lines.append(f"  size-adjust: {percent(entry['size_adjust'])};")
    if entry["overrides"]:
        lines.append(f"  ascent-override: {percent(entry['overrides']['ascent'])};")
        lines.append(f"  descent-override: {percent(entry['overrides']['descent'])};")
        lines.append(f"  line-gap-override: {percent(entry['overrides']['line_gap'])};")
    lines.append("}")
    return "\n".join(lines)


def build(fonts_dir: Path, coverage_path: Path, css_path: Path, manifest: dict, pin: bool) -> dict:
    """Write every output; returns the pins recorded when `pin` is set."""
    pins: dict = {}
    metrics = inter_metrics()
    built: dict[str, TTFont] = {}
    entries: dict[str, dict] = {}

    for face in manifest["faces"]:
        print(f"{face['file']}")
        report: dict = {}
        license_bytes = fetch(face["license_url"])
        pinned(face, "license_sha256", license_bytes, pin, pins)
        source = fetch(face["font_url"])
        pinned(face, "font_sha256", source, pin, pins)
        reserved = reserved_names(license_bytes.decode("utf-8"))

        if face["mode"] == "verbatim":
            output = source
            charset(face, load(source).getBestCmap(), report)
        elif face["mode"] == "subset":
            output = build_subset(face, source, reserved, report)
        else:
            raise BuildError(f"{face['file']}: unknown mode {face['mode']!r}")

        (fonts_dir / face["file"]).write_bytes(output)
        (fonts_dir / face["license_file"]).write_bytes(license_bytes)
        font = load(output)
        built[face["file"]] = font
        unicode_range = parse_ranges(face["unicode_range"])
        codepoints = {cp for cp in font.getBestCmap() if in_ranges(cp, unicode_range)}
        entries[face["file"]] = {
            "css_family": face["css_family"],
            "sha256": sha256(output),
            "bytes": len(output),
            "weight": face["weight"],
            "license_file": face["license_file"],
            "locales": face["locales"],
            "unicode_range": ", ".join(f"U+{item}" for item in face["unicode_range"]),
            "size_adjust": 100,
            "overrides": None,
            "codepoints": coverage_ranges(codepoints),
        }
        for label, count in report.items():
            print(f"  {label}: {count}")
        print(f"  reserved names: {reserved or 'none'}; covered codepoints: {len(codepoints)}; bytes: {len(output)}")

    # Metrics need every face built: size-adjust compares a glyph against another output face.
    for face in manifest["faces"]:
        entry = entries[face["file"]]
        match = face.get("size_adjust")
        if match:
            glyph = int(match["glyph"], 16)
            this, other = built[face["file"]], built[match["match"]]
            for font in (this, other):
                if default_weight(font) != 400:
                    raise BuildError(f"{face['file']}: size-adjust needs both faces to default to wght 400")
            ratio = glyph_height(other, glyph) / glyph_height(this, glyph)
            entry["size_adjust"] = round(ratio * 200) / 2
            print(f"{face['file']}: size-adjust {entry['size_adjust']}% (raw {ratio * 100:.3f}%)")
        if face["metrics"] == "inter":
            scale = entry["size_adjust"] / 100
            entry["overrides"] = {key: round(value / scale * 100, 2) for key, value in metrics.items()}
            print(f"{face['file']}: overrides {entry['overrides']}")
        elif face["metrics"] != "natural":
            raise BuildError(f"{face['file']}: unknown metrics {face['metrics']!r}")

    families = committed_families()
    files = dict(entries)
    for file in manifest["committed"]:
        data = (FONTS_DIR / file).read_bytes()
        files[file] = {
            "css_family": families[file],
            "sha256": sha256(data),
            "codepoints": coverage_ranges(set(load(data).getBestCmap())),
        }
    coverage = {"fonttools": manifest["fonttools"], "inter_metrics": metrics, "files": files}
    coverage_path.write_text(to_json(coverage) + "\n", encoding="utf-8")

    blocks = [font_face_css(face, entries[face["file"]]) for face in manifest["faces"]]
    css_path.write_text(CSS_HEADER + "\n\n" + "\n\n".join(blocks) + "\n", encoding="utf-8")
    return pins


def outputs(manifest: dict) -> list[str]:
    """Relative names of every font-directory output."""
    names = []
    for face in manifest["faces"]:
        for name in (face["file"], face["license_file"]):
            if name not in names:
                names.append(name)
    return names


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--pin", action="store_true", help="record sha256 values that are still empty")
    mode.add_argument("--check", action="store_true", help="rebuild into a temp dir and compare with committed files")
    args = parser.parse_args()

    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    if fontTools.version != manifest["fonttools"]:
        raise BuildError(f"fontTools {fontTools.version} installed, fonts.json requires {manifest['fonttools']}")

    if not args.check:
        pins = build(FONTS_DIR, COVERAGE, SCRIPT_FONTS_CSS, manifest, args.pin)
        if pins:
            write_pins(pins)
            print(f"pinned {len(pins)} sha256 values in {MANIFEST.relative_to(REPO_ROOT)}")
        return 0

    with tempfile.TemporaryDirectory(prefix="sbfonts-") as temp:
        temp_dir = Path(temp)
        build(temp_dir, temp_dir / COVERAGE.name, temp_dir / SCRIPT_FONTS_CSS.name, manifest, pin=False)
        pairs = [(temp_dir / name, FONTS_DIR / name) for name in outputs(manifest)]
        pairs += [(temp_dir / COVERAGE.name, COVERAGE), (temp_dir / SCRIPT_FONTS_CSS.name, SCRIPT_FONTS_CSS)]
        mismatched = 0
        for rebuilt, committed in pairs:
            expected = sha256(rebuilt.read_bytes())
            actual = sha256(committed.read_bytes()) if committed.exists() else "missing"
            status = "ok" if expected == actual else "MISMATCH"
            mismatched += expected != actual
            print(f"{status:8} {expected[:16]} {committed.relative_to(REPO_ROOT)}")
    if mismatched:
        print(f"{mismatched} output(s) differ from a fresh build", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except BuildError as error:
        print(f"error: {error}", file=sys.stderr)
        sys.exit(1)
