// Copyright (c) 2024-2026 ScreenerBot (screenerbot.io)
// SPDX-License-Identifier: BUSL-1.1
//

/**
 * Bundled per-script fonts: the committed binaries, their @font-face rules and the font tokens
 * must together render every catalog character of the non-Latin locales with bundled faces only.
 *
 * `tools/fonts/coverage.json` is generated by `tools/fonts/build_fonts.py` with the sha256 and
 * the effective codepoint coverage of every bundled font. A new catalog character outside the
 * subset fails here; re-run the tool, which adds catalog characters to the subsets.
 *
 * Run with `npm run test:js`.
 */

import test from "node:test";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFileSync, readdirSync, statSync } from "node:fs";
import { join, resolve } from "node:path";
import postcss from "postcss";

import { REPO_ROOT } from "../lib/dashboard_ui.mjs";
import { loadCatalogs } from "../i18n/catalogs.mjs";

const FONTS_DIR = resolve(REPO_ROOT, "src/webserver/assets/fonts");
const STYLES_DIR = resolve(REPO_ROOT, "src/webserver/templates/styles");
const FOUNDATION_CSS = join(STYLES_DIR, "foundation.css");
const SCRIPT_FONTS_CSS = join(STYLES_DIR, "base/script_fonts.css");
const COVERAGE = JSON.parse(readFileSync(resolve(REPO_ROOT, "tools/fonts/coverage.json"), "utf8"));
const MANIFEST = JSON.parse(readFileSync(resolve(REPO_ROOT, "tools/fonts/fonts.json"), "utf8"));

const SCRIPT_LOCALES = ["zh-Hans", "ja", "ko", "hi", "ar", "fa"];
const TOKENS = ["--font-sans", "--font-mono", "--font-data"];
/** Faces that may render text in every locale: Latin, Cyrillic, Vietnamese, digits, symbols. */
const UNIVERSAL_FAMILIES = new Set(["Inter", "JetBrains Mono"]);
const SKIPPED = /[\p{Default_Ignorable_Code_Point}\p{Extended_Pictographic}]/u;
const OS_FALLBACK_ALLOWED = new Set(MANIFEST.os_fallback_allowed.map((hex) => parseInt(hex, 16)));

const unquote = (value) => value.trim().replace(/^["']|["']$/g, "");

/** `U+3000-303F, U+25CC` as inclusive [low, high] pairs. */
function parseUnicodeRange(value) {
  return value.split(",").map((part) => {
    const [low, high = low] = part.trim().replace(/^U\+/i, "").split("-");
    return [parseInt(low, 16), parseInt(high, 16)];
  });
}

const inRanges = (codepoint, ranges) =>
  ranges.some(([low, high]) => low <= codepoint && codepoint <= high);

/** Top-level comma split, so `var(--a, b)` stays whole. */
function splitList(value) {
  const parts = [];
  let depth = 0;
  let current = "";
  for (const char of value) {
    if (char === "(") depth += 1;
    else if (char === ")") depth -= 1;
    if (char === "," && depth === 0) {
      parts.push(current.trim());
      current = "";
    } else {
      current += char;
    }
  }
  if (current.trim()) parts.push(current.trim());
  return parts;
}

/** family -> [{ file, unicodeRange, ranges }] from the @font-face rules of both stylesheets. */
function fontFaces() {
  const faces = new Map();
  for (const path of [FOUNDATION_CSS, SCRIPT_FONTS_CSS]) {
    postcss.parse(readFileSync(path, "utf8")).walkAtRules("font-face", (rule) => {
      const decls = {};
      rule.walkDecls((decl) => {
        decls[decl.prop] = decl.value;
      });
      const family = unquote(decls["font-family"]);
      const file = decls.src.match(/url\(["']?\/assets\/fonts\/([^"')]+)["']?\)/)[1];
      const unicodeRange = decls["unicode-range"] ?? null;
      const entry = {
        family,
        file,
        unicodeRange,
        ranges: unicodeRange ? parseUnicodeRange(unicodeRange) : null,
      };
      faces.set(family, [...(faces.get(family) ?? []), entry]);
    });
  }
  return faces;
}

/**
 * Font tokens for a locale: base values from rules whose selector list contains `:root` or
 * `[lang]`, then overrides from `[lang]:lang(<primary subtag>)` selectors.
 */
function tokensFor(code) {
  const primary = code.split("-")[0];
  const base = {};
  const overrides = {};
  postcss.parse(readFileSync(FOUNDATION_CSS, "utf8")).walkRules((rule) => {
    const selectors = rule.selectors.map((selector) => selector.trim());
    const isBase = selectors.some((selector) => selector === ":root" || selector === "[lang]");
    const isOverride = selectors.some(
      (selector) => selector.match(/^\[lang\]:lang\((\w+)\)$/)?.[1] === primary
    );
    if (!isBase && !isOverride) return;
    rule.walkDecls((decl) => {
      if (decl.prop !== "--font-script" && !TOKENS.includes(decl.prop)) return;
      (isOverride ? overrides : base)[decl.prop] = decl.value;
    });
  });
  const values = { ...base, ...overrides };
  const script = values["--font-script"];
  return Object.fromEntries(
    TOKENS.map((token) => [
      token,
      splitList(values[token].replaceAll("var(--font-script)", script)).map(unquote),
    ])
  );
}

/** Coverage pairs of a file, as recorded by the build tool. */
function coverageOf(file) {
  const entry = COVERAGE.files[file];
  assert.ok(entry, `${file} is referenced by @font-face but missing from coverage.json`);
  return entry.codepoints;
}

/** The first bundled face in `families` that renders `codepoint`, or null. */
function resolveFace(codepoint, families, faces) {
  for (const family of families) {
    for (const face of faces.get(family) ?? []) {
      if (face.ranges && !inRanges(codepoint, face.ranges)) continue;
      if (inRanges(codepoint, coverageOf(face.file))) return face;
    }
  }
  return null;
}

/** Why `codepoint` fails for locale `code`, or null when a permitted bundled face renders it. */
function codepointError(code, codepoint, families, faces) {
  const face = resolveFace(codepoint, families, faces);
  const label = `U+${codepoint.toString(16).toUpperCase().padStart(4, "0")} ${String.fromCodePoint(codepoint)}`;
  if (!face) return `${label}: no bundled face covers it`;
  if (UNIVERSAL_FAMILIES.has(face.family)) return null;
  const locales = COVERAGE.files[face.file].locales ?? [];
  return locales.includes(code)
    ? null
    : `${label}: resolves to ${face.family}, which is not a ${code} face`;
}

function catalogCodepoints(files, serverOnly) {
  const codepoints = new Set();
  for (const [name, text] of Object.entries(files)) {
    if (serverOnly.has(name.replace(/\.ftl$/, ""))) continue;
    for (const char of text) {
      const codepoint = char.codePointAt(0);
      if (codepoint < 0x80 || SKIPPED.test(char) || OS_FALLBACK_ALLOWED.has(codepoint)) continue;
      codepoints.add(codepoint);
    }
  }
  return [...codepoints].sort((a, b) => a - b);
}

function registryNames() {
  const toml = readFileSync(resolve(REPO_ROOT, "locales/registry.toml"), "utf8");
  return new Map(
    [...toml.matchAll(/^\s*code\s*=\s*"([^"]+)"\s*\n\s*name\s*=\s*"([^"]+)"/gm)].map((m) => [
      m[1],
      m[2],
    ])
  );
}

function walkCss(dir) {
  return readdirSync(dir).flatMap((name) => {
    const path = join(dir, name);
    if (statSync(path).isDirectory()) return walkCss(path);
    return path.endsWith(".css") ? [path] : [];
  });
}

const FACES = fontFaces();
const bundledFiles = Object.keys(COVERAGE.files);
const scriptFiles = bundledFiles.filter((file) => COVERAGE.files[file].unicode_range);

test("every coverage.json file matches the committed bytes", () => {
  const mismatched = bundledFiles.filter((file) => {
    const bytes = readFileSync(join(FONTS_DIR, file));
    return createHash("sha256").update(bytes).digest("hex") !== COVERAGE.files[file].sha256;
  });
  assert.deepEqual(mismatched, [], "re-run tools/fonts/build_fonts.py");
});

test("@font-face rules and the coverage manifest agree", () => {
  const all = [...FACES.values()].flat();
  const unknown = all.filter((face) => !COVERAGE.files[face.file]).map((face) => face.file);
  assert.deepEqual(unknown, [], "@font-face src files missing from coverage.json");
  for (const file of scriptFiles) {
    const entry = COVERAGE.files[file];
    const rules = all.filter((face) => face.file === file);
    assert.equal(rules.length, 1, `${file}: expected exactly one @font-face`);
    assert.equal(rules[0].family, entry.css_family, `${file}: font-family`);
    assert.equal(rules[0].unicodeRange, entry.unicode_range, `${file}: unicode-range`);
  }
});

test("every catalog character of a script locale renders in bundled fonts", async () => {
  const { catalogs, serverOnly } = await loadCatalogs();
  const failures = [];
  for (const code of SCRIPT_LOCALES) {
    const tokens = tokensFor(code);
    const codepoints = catalogCodepoints(catalogs[code], serverOnly);
    assert.ok(codepoints.length > 0, `${code}: no catalog characters found`);
    for (const token of TOKENS) {
      for (const codepoint of codepoints) {
        const error = codepointError(code, codepoint, tokens[token], FACES);
        if (error) failures.push(`${code} ${token} ${error}`);
      }
    }
  }
  assert.deepEqual(failures, []);
});

test("every registered locale name renders in its own --font-sans", async () => {
  const { registered } = await loadCatalogs();
  const names = registryNames();
  const failures = [];
  for (const code of registered) {
    const name = names.get(code);
    assert.ok(name, `${code}: no name in registry.toml`);
    const families = tokensFor(code)["--font-sans"];
    for (const char of name) {
      const codepoint = char.codePointAt(0);
      if (codepoint < 0x80 || SKIPPED.test(char)) continue;
      if (!resolveFace(codepoint, families, FACES))
        failures.push(`${code} ${name}: U+${codepoint.toString(16)} ${char}`);
    }
  }
  assert.deepEqual(failures, []);
});

test("the resolver rejects uncovered and foreign-script characters", () => {
  const ja = tokensFor("ja")["--font-sans"];
  // 龘 is outside every subset: nothing bundled covers it.
  assert.match(codepointError("ja", 0x9f98, ja, FACES), /no bundled face covers it/);
  // Hangul in the ja stack resolves to the Korean face, which is not a ja face.
  assert.match(
    codepointError("ja", 0xd55c, ja, FACES),
    /ScreenerBot Sans KR, which is not a ja face/
  );
  // Positive controls: kana in the Japanese face, Latin in Inter.
  assert.equal(codepointError("ja", 0x3042, ja, FACES), null);
  assert.equal(codepointError("ja", 0xe9, ja, FACES), null);
});

test("stylesheets set font-family only through the font tokens", () => {
  const violations = [];
  for (const path of walkCss(STYLES_DIR)) {
    postcss.parse(readFileSync(path, "utf8")).walkDecls((decl) => {
      if (decl.parent?.type === "atrule" && decl.parent.name === "font-face") return;
      if (decl.prop !== "font-family" && decl.prop !== "font") return;
      const value = decl.value.trim();
      if (value === "inherit" || value.includes("var(--font-")) return;
      violations.push(
        `${path.slice(STYLES_DIR.length + 1)}:${decl.source.start.line}: ${decl.prop}: ${value}`
      );
    });
  }
  assert.deepEqual(violations, []);
});
